Map barcode scan listener params
goodeggs/angular-barcode-listener pull request #16
Opened 2018-05-09 20:25 UTC by darkurse

Hi @serhalp , 
I am still struggling with the tests.. Could you give me a suggestion on how to do this please ?

Thanks

2018-05-17 04:09 UTC, serhalp requested changes
Generally looks good. Just a few comments inline. Could you also please remove the workaround? I've fixed the bug in barcode-scan-listener and bumped it in here on master (just rebase against master). Thank you for jumping in!

2018-05-17 04:09 UTC, serhalp commented on src/index.coffee
> +      barcodeValueTest: if !!scope.valueTest then new RegExp(scope.valueTest) else undefined
Use existence operator `scope.valueTest?` here instead of `!!scope.valueTest`

2018-05-17 04:09 UTC, serhalp commented on src/index.coffee
> +      finishScanOnMatch: if scope.finishScanOnMatch then scope.finishScanOnMatch == 'true' else true
I'd rather not duplicate the default `finishScanOnMatch` param value from the underlying [barcode-scan-listener](https://github.com/goodeggs/barcode-scan-listener/blob/cc372082507dd4b74570b03e5bb7435bb2c9353c/src/index.js#L22-L24). How about `else undefined` here instead of `else true` so that barcode-scan-listener applies its own default?

2018-05-17 04:09 UTC, serhalp commented on src/index.coffee
> +  call the scanHandler with the value. This will generally make scans faster.
could you also please add these two params to the README?

2018-05-17 04:09 UTC, serhalp commented on src/index.coffee
>      removeScanListener = barcodeScanListener.onScan {
update [this test](https://github.com/goodeggs/angular-barcode-listener/blob/470cedac1eb89f0aab10b584fdbf5a0172d274cd/test/angular_barcode_listener.test.coffee#L26) to assert that it passes the two new params?

2018-05-17 04:09 UTC, serhalp commented on package-lock.json
> +{
can you remove this and rebase on master? I've updated the repo to use yarn.

2018-05-21 13:02 UTC, darkurse commented
Sorry, I forgot to rebase a couple of files. I hope I didn't forget anything this time.

2018-05-23 19:43 UTC, darkurse commented
Any chance you can get a look at this to finalise the PR  ? I'll need to generate a new release with these changes at the end of the week

2018-05-31 08:32 UTC, darkurse commented
@serhalp ?

2018-06-04 21:10 UTC, dannynelson approved these changes

2018-06-04 21:10 UTC, merged

2018-06-04 21:27 UTC, dannynelson commented
Sorry for the delay, @darkurse. We published your changes at `angular-barcode-listener@3.0.0`.